# Generated by Django 4.2.3 on 2023-08-15 12:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_listing_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='distance_to_gate',
            field=models.IntegerField(default=10, validators=[django.core.validators.MaxValueValidator(24, 'distane must not exceed 24 24')], verbose_name='Distance in meters'),
        ),
        migrations.AddField(
            model_name='listing',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='is your list sitll active'),
        ),
        migrations.AddField(
            model_name='listing',
            name='is_availaible',
            field=models.BooleanField(default=True, verbose_name='is the listing available'),
        ),
        migrations.AddField(
            model_name='listing',
            name='utilities',
            field=models.CharField(default=None, max_length=500, verbose_name='list the utilities in your house'),
        ),
    ]
