# Generated by Django 4.2.3 on 2023-08-14 11:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landlords', '0003_alter_landlord_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landlord',
            name='phone_number',
            field=models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message='Phone number must be entered in the format: "070xxxxxxxx". 11 digits allowed.', regex='^0[789][01]{9}$')]),
        ),
    ]
